InconspicuousPaprika/Car.ly

package.json
src/actions/favoritesActions.js
src/actions/loadActions.js
src/actions/loginActions.js
src/actions/matchActions..js
src/actions/searchActions.js
src/api/index.js
src/reducers/favorites.js
src/reducers/index.js
src/reducers/login.js
src/reducers/match.js
src/service/backend.js

**READY**
NO
add additional files and folders to the files structure and mapped out action types.
none, continue to test on computer
```sh
```
1. 
*

prep actions reducers

---

src/api/service/autotrader.js

**READY**
NO
Built out autrader api
branch | PR
```sh
```
1. 
*

implement autotrader api

---

ios/Carly.xcodeproj/project.pbxproj
package.json
src/components/Login.js

**READY**
NO
Added email and password to login 
branch | PR
```sh
```
1. 
*

Added email and password to login.

---

android/app/build.gradle
android/app/src/main/java/com/carly/MainActivity.java
android/app/src/main/res/values/strings.xml
android/settings.gradle
ios/Carly.xcodeproj/project.pbxproj
src/components/Login.js

IN DEVELOPMENT
NO
Fixed connection issue with missing node_modules
branch | PR
```sh
```
1. 
*

Fixed connection issue

---

src/components/Login.js

YES | NO
branch | PR
```sh
```
1. 
*

Added signup features

---

src/components/Signup.js
src/index.js

YES | NO
branch | PR
```sh
```
1. 
*

Signupview

---

src/components/Login.js
src/server/controllers/userController.js
src/server/models/userModel.js
src/server/routes.js

IN DEVELOPMENT
NO
Adds signup server route, needs hashing/salting of password
branch | PR
```sh
```
1. 
*

Added signup server route, successful post test on postman

---

src/actions/searchActions.js
src/actions/setQueryAction.js
src/components/Counter.js
src/reducers/search.js

**READY**
NO
branch | PR
```sh
```
1. 
*

refactor to update query object without async

---

ios/Carly.xcodeproj/project.pbxproj
package.json
src/actions/searchActions.js
src/components/Counter.js
src/containers/App.js
src/reducers/search.js
src/service/backend.js

IN DEVELOPMENT
NO
Saves async api data to state
branch | PR
-Process async api data
1. 
* Search

Apitostate

---

ios/Carly.xcodeproj/project.pbxproj
src/actions/resultsActions.js
src/api/photoSearch.js
src/components/Results.js
src/components/resultsInput.js
src/components/resultsList.js
src/constants/searchActionTypes.js
src/containers/App.js
src/reducers/index.js
src/reducers/photos.js

**READY**
NO
Store retrieve data in state and display on results page.
branch | PR
1. 
* Results component

Displayapidata

---

ios/Carly.xcodeproj/project.pbxproj
src/schemas.sql
src/server/controllers/userController.js
src/server/models/userModel.js

YES | NO
branch | PR
```sh
```
1. 
*

fixed merge conflict in xcode proj

---

src/assets/carDirectory.js

IN DEVELOPMENT
NO
Adds a list of cars for search page
branch | PR
```sh
```
1. 
*

Added makes and models to car directory

---

ios/Carly.xcodeproj/project.pbxproj
src/containers/App.js
src/server/models/userModel.js

YES | NO
branch | PR
```sh
```
1. 
*

minor changes

---

src/schemas.sql

YES | NO
branch | PR
```sh
```
1. 
*

Updated schema design

---

package.json

YES | NO
branch | PR
```sh
```
1. 
*

uninstall material ui

---

ios/Carly.xcodeproj/project.pbxproj
package.json

YES | NO
branch | PR
```sh
```
1. 
*

resolve projectfile issues

---

package.json

YES | NO
branch | PR
```sh
```
1. 
*

installed and saved bluebird

---

src/actions/resultsActions.js
src/components/resultsList.js
src/containers/App.js
src/server/controllers/userController.js
src/server/models/userModel.js
src/server/routes.js
src/service/backend.js

YES | NO
branch | PR
```sh
```
1. 
*

printing user ID

---

src/actions/sendPostDataLoginAction.js
src/actions/signupSubmitAction.js
src/components/Login.js
src/containers/App.js
src/reducers/login.js
src/schemas.sql
src/server/models/userModel.js
src/service/backend.js
src/utils/getResponse.js

YES | NO
branch | PR
```sh
```
1. 
*

Localstorage

---

src/components/Login.js

**READY**
NO
branch | PR
```sh
```
1. 
*

Added styling to login page

---

src/containers/App.js

YES | NO
branch | PR
```sh
```
1. 
*

include Favorites scene

---

src/actions/searchActions.js
src/components/Card.js
src/components/Search.js
src/reducers/search.js
src/service/backend.js

IN DEVELOPMENT
NO
Results from multiple API calls are now combined and set to state. Tinder cards have also been resized.
branch | PR
```sh
```
1. 
*

Multiple APIs

---

src/components/Card.js
src/components/Results.js

IN DEVELOPMENT
NO
Added price and mileage to card
branch | PR
```sh
```
1. 
*

add price and mileage to card

---

src/actions/searchActions.js
src/components/Card.js
src/service/backend.js
src/utils/getResponse.js

READY
NO
all three extractors are now available in backend.js
branch | PR
```sh
```
1. 
*

implement autoTempest extractor

---

src/components/Card.js

READY
NO
card render function is now conditional on data completeness
branch | PR
```sh
```
1. 
*

implemented ternary return for Card render function

---

src/components/Card.js
src/components/Results.js

IN DEVELOPMENT
NO
Global styles applied to results and card components.
branch | PR
```sh
```
1. 
*

applied globalStyles to results and card

---

src/components/Login.js
src/containers/App.js
src/reducers/login.js

YES | NO
branch | PR
```sh
```
1. 
*

added alert message

---

src/components/Search.js

YES | NO
branch | PR
```sh
```
1. 
*

onPress Search routes to Results

---

src/actions/faceBookAction.js
src/components/fbLogin.js
src/reducers/login.js

**READY**
NO
branch | PR
```sh
```
1. 
*

Set up asyncStorage for facebook token

---

src/actions/searchActions.js
src/components/Login.js
src/components/Results.js
src/service/backend.js
src/utils/getResponse.js

**IN DEVELOPMENT**
NO
branch | PR
```sh
```
1. 
*

Adjusted search queries to store in favorites

---

ios/Carly/Info.plist
src/actions/searchActions.js
src/components/Favorite.js
src/components/Results.js
src/containers/App.js
src/schemas.sql
src/server/models/favoriteModel.js
src/service/backend.js
src/utils/getResponse.js

IN DEVELOPMENT
NO
Implemented facebook favoriting and trucar extractor (please rebuild your schemas)
branch | PR
```sh
```
1. 
*

Facebookfavorite

---

src/components/PricePicker.js
src/components/YearPicker.js
src/components/ZipCodeContainer.js
src/styles/SearchGlobalStyles.js

YES | NO
branch | PR
```sh
```
1. 
*

Added styling to search page
